version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    ports:
      - "5672:5672"   # AMQP 协议端口
      - "15672:15672" # 管理界面端口
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - rabbitmq_network
    restart: always

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log:
